#!/bin/sh

# build
cargo build

# test
cargo test

# format the code and commit it
cargo fmt

# commit the code when it's formatted
git add .
git diff --quiet && git diff --staged --quiet || git commit -m "format"
