tab_spaces=2
normalize_comments=true
overflow_delimited_expr=true
reorder_impl_items=true
use_field_init_shorthand=true
where_single_line=true
where_single_line=true
report_fixme="Unnumbered"
report_todo="Unnumbered"
imports_granularity="Item"
match_block_trailing_comma=true
control_brace_style="ClosingNextLine"
